definitions:
  response.Response:
    properties:
      code:
        type: string
      data:
        type: object
    type: object
info:
  contact:
    email: truongnlbse140940@fpt.edu.vn
    name: NGUYEN LE BAO TRUONG
    url: https://github.com/allvisss
  description: Elliptic Curve Cryptography service API for IOT system
  termsOfService: http://swagger.io/terms/
  title: ECC SERVICE API
  version: "0.0"
paths:
  /v1/test:
    get:
      consumes:
      - '*/*'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.Response'
            type: array
      summary: Testing API GET method
      tags:
      - Auth
swagger: "2.0"
